### ISSUE TITLE
Creating a new game: the board (Autumn)

### ISSUE THREAD

**Issue by foxfriends** [foxfriends/root#23]
When creating a new game, the board needs to be constructed. Let's start with the Autumn map for now, the others can come later. This will be a lot of data entry, but would be an easier issue if interested in trying out some Rust code. Otherwise, I will get to it a bit at a time. There will be many more pieces to create in future issues.

As part of the `Board::create` method (which is used by `Game::create`), the following fields should be populated with data that represents a Root board:
- [x] `positions`: one entry for each position on the board where someone could place a piece (clearings and forests)
- [x] `clearings`: a marker for which positions correspond to clearings, suits should be randomized if not on the Autumn map
- [ ] `forests`: a marker for which positions correspond to forests
- [ ] `water`: a marker for which clearings contain water
- [ ] `connections`: a connection between any pair of positions where a move could happen (clearing to clearing, forest to forest, clearing to forest)
- [ ] `rivers`: a river between two clearings (similar to a connection)
- [ ] `ferry`: the position where the ferry is, if on the Lake map
- [ ] `tower`: the position where the tower is, if on the Caves map

Feel free to take it one field at a time. The order above should be reasonable. I started a few, hopefully giving some idea of what's going on. 

Each model will need a function `pub fn new(..) -> Self`, and potentially some accessors for fields, if they are necessary. If you are comfortable with it, the `async fn save(&self, game: &str, conn: &mut PgConnection) -> sqlx::Result<()>` method would also be nice to have, but `sqlx` can be a bit tricky sometimes.

**Comment by foxfriends** [comment]
Hey, just letting you know I went ahead and did this one! Took a break for a while there over the holidays but will be getting back into this. Time to move on to the game logic!

**Comment by agdust** [comment]
Oh, that's cool!

Sorry, I couldn't figure out how to work with this setup with -acceptable- speed. In nearest I don't think I will be able to do something in project, but I will try to stay in touch and may be with time will do some tasks with assets or frontend part
